### ISSUE TITLE
Duplicate updates

### ISSUE THREAD

**Issue by Luna-devv** [replugged-org/replugged#82] opened 2022-08-10 12:06 UTC
**Describe the bug**
In my updater, updates from replugged were displayed under a plugin (`Heyven`) as well
![](https://c.lunish.nl/r/VeqS.png)

**To Reproduce**
Probably installing [Heyvem](https://github.com/french-goose/heyven) and waiting for a replugged update

**Expected behavior**
Updates are only under "replugged"

**Desktop (please complete the following information):**
Canary 140710 (b2e1a7b)
Host 1.0.48
Windows 11 64-Bit (10.0.25174)
Replugged main (ed66152)

**Additional context**
 - [ ] I checked if Discord and/or Replugged are up to date (cant be since the updater is the issue)
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by asportnoy** [comment] 2022-08-10 12:37
Oops, this wasn't related to the above issue. Reopening

**Comment by Wolfkid200444** [comment] 2022-08-10 12:38
Ive gotten this issue before but i simply remove the plugins on the list and downloaded them again maybe this will help

**Comment by Snare-Hawk** [comment] 2022-09-02 15:26
this also happen with me and has ever i got the bot-details plugin and spans from update to update

![fff7b99](https://user-images.githubusercontent.com/85657152/188182661-b782428e-2022-4c8f-b136-816f2dc4f8c1.png)
![ac3e573](https://user-images.githubusercontent.com/85657152/188182663-4d5166ce-fefc-4047-a888-ccc864b2597e.png)
![265d09d](https://user-images.githubusercontent.com/85657152/188182664-1fa4436d-cf4c-4314-bedd-0b8f1ea5b1dc.png)

**Comment by Snare-Hawk** [comment] 2022-09-02 22:30
when trying to reload the plugin, it gave the error that a ".git" folder was not found but it seemed to be present when i looked at it myself
upon uninstalling and then reinstalling the plugin, it did not show again in the updates tab, so i believe that bug to be the cause of this

**Comment by asportnoy** [comment] 2022-09-02 22:33
Sounds about right to me. @Luna-devv, can you try that? If so, this is probably just a one-off thing.

**Comment by asportnoy** [comment] 2022-12-10 22:32
Closing this due to the rewrite.

**Closed by asportnoy** 2022-12-10 22:32 UTC
Labels: bug
