### ISSUE TITLE
Autocomplete not showing

### ISSUE THREAD

**Issue by DracoClaw** [replugged-org/replugged#120] opened 2022-08-17 21:09 UTC
**Describe the bug**
The autocomplete of Replugged command args is not showing.

**To Reproduce**
type a command that should have args, such as .disable

**Expected behavior**
The expected behavior would be a list of themes and plugins appears

**Desktop (please complete the following information):**
Windows 10 64-Bit (10.0.19043)
Replugged main (940565c)

**Additional context**
 - [x] I checked if Discord and/or Replugged are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 

https://user-images.githubusercontent.com/34274162/185243550-25742301-2348-45bc-a7a4-fdacb06ad2bf.mp4

**Comment by asportnoy** [comment] 2022-08-20 04:01
Can't reproduce

**Comment by asportnoy** [comment] 2022-08-27 01:18
Closing this since I didn't get any more info

**Closed** 2022-08-27 01:19 UTC
Labels: bug, needs more info
